### ISSUE TITLE
latest update not detecting fate go jp

### ISSUE THREAD

**Issue by screenpass1160** [rayshift/translatefgo#64] opened 2022-09-30 18:44 UTC
using latest version of bluestacks, tried to delete cache and reopened game, next step may be re-installing fate go jp to see if it detects either game version. The app stops after pressing "continue"

**Comment by Ninlyl** [comment] 2022-09-30 21:02
I got the same Issue, The 2.0.8 worked just fine, but now  the 2.0.9 can't detect my game, and the app close when I click on fgo jp and na.

**Comment by neobenedict** [comment] 2022-09-30 23:01
Are you both on bluestacks?

I know what the issue is, it's because bluestacks uses a non-standard version of android that doesn't support what this app is now using to perform the translation. I will have to likely implement the old method again for bluestacks users. Alternatively you can try a different emulator like nox or ldplayer.

**Comment by KuroVG95** [comment] 2022-10-01 01:52
I'm having the same problem here, and unfortunately, Bluestacks is the only emulator that works on my PC. I've already tried Nox or LDPlayer as recommended, but they don't work. And that had to happen right now that I was going to start reading Iyo's event.
I would really appreciate it if you guys release another update that will work on Bluestcks again.

**Comment by neobenedict** [comment] 2022-10-01 02:23
What I have done is make the update optional. If you uninstall the app and install 2.0.8 instead, it might work for now. Let me know. I will try and fix it for 2.0.10.

**Comment by KuroVG95** [comment] 2022-10-01 02:33
Following your advice of going for the 2.0.8 version worked just fine. At least for now.
Thanks mate.

**Comment by neobenedict** [comment] 2022-10-02 17:31
Can you try upgrading to the 64-bit version of bluestacks?

**Comment by screenpass1160** [comment] 2022-10-02 17:35
the previous version is working on 32 bit, am downloading the 64 bit version to see how it goes

**Comment by neobenedict** [comment] 2022-10-08 19:36
Fixed with 2.1.0.

**Closed by neobenedict** 2022-10-08 19:36 UTC
